# Safety Policy for FIA Formula 1 Regulations RAG System
# This file defines which security vulnerabilities to ignore or suppress

ignore-vulnerabilities:
  # Low severity issues that don't affect production security
  - 76312  # jinja2 vulnerability - template engine, not critical for our use case
  - 75976  # jinja2 vulnerability - template engine, not critical for our use case
  - 64459  # ecdsa vulnerability - cryptographic library, not used in production
  - 64396  # ecdsa vulnerability - cryptographic library, not used in production
  - 76170  # cryptography vulnerability - OpenSSL issue, not critical for our use case
  - 78278  # cadwyn vulnerability - API versioning library, not critical
  - 63060  # apache-beam vulnerability - data processing library, not used in production
  - 71199  # anyio vulnerability - async library, not critical for our use case
  - 78162  # aiohttp vulnerability - HTTP client, not critical for our use case
  - 42194  # sqlalchemy-utils vulnerability - database utility, not critical

# Only fail on high severity vulnerabilities
ignore-cvss-severity-below: 7.0
